name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [ Release ]
        build_bits: [ 32, 64 ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake for 32-bit build
      if: ${{ matrix.build_bits == '32' }}
      run: cmake -A Win32 -B ${{ github.workspace }}/Build${{ matrix.build_bits }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Configure CMake for 64-bit build
      if: ${{ matrix.build_bits == '64' }}
      run: cmake -A x64 -B ${{ github.workspace }}/Build${{ matrix.build_bits }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{ github.workspace }}/Build${{ matrix.build_bits }} --config ${{ matrix.build_type }}
