name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows_msvc:
    runs-on: windows-latest

    strategy:
      matrix:
        type: [ Release ]
        bits: [ 32, 64 ]

    env:
      BUILD_DIR: ${{ github.workspace }}/Build${{ matrix.bits }}
      BUILD_PLATFORM: ${{ matrix.bits == '32' && 'Win32' || 'x64' }}
      EXE_PATH: ${{ github.workspace }}/Build${{ matrix.bits }}/${{ matrix.type }}/CryMP-Client${{ matrix.bits }}.exe

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -A ${{ env.BUILD_PLATFORM }} -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ matrix.type }}

    - name: Build
      run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.type }}

    - name: Hash
      run: ('EXE_HASH=' + (Get-FileHash -Algorithm SHA256 ${{ env.EXE_PATH }}).Hash.ToLower()) >> $Env:GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CryMP-Client${{ matrix.bits }}-${{ env.EXE_HASH }}
        path: ${{ env.EXE_PATH }}
