name: Build

on:
  push:
    branches:
    - '**'

jobs:
  build_windows_msvc:
    runs-on: windows-latest

    strategy:
      matrix:
        type: [ RelWithDebInfo ]
        bits: [ 32, 64 ]

    env:
      BUILD_DIR: ${{ github.workspace }}/Build${{ matrix.bits }}
      BUILD_PLATFORM: ${{ matrix.bits == '32' && 'Win32' || 'x64' }}
      RESULT: ${{ github.workspace }}/Build${{ matrix.bits }}/${{ matrix.type }}/CryMP-Client${{ matrix.bits }}

    steps:
    - uses: actions/checkout@v3

    - name: Get Ninja
      run: |
        $release = Invoke-RestMethod 'https://api.github.com/repos/ninja-build/ninja/releases/latest'
        $release
        $asset = $release.assets | where { $_.name -eq 'ninja-win.zip' }
        $asset
        $ninja = Join-Path $env:BUILD_DIR 'ninja-win'
        $ninja
        Invoke-WebRequest $asset.browser_download_url -OutFile ($ninja + '.zip')
        Expand-Archive ($ninja + '.zip') -DestinationPath $ninja
        $env:PATH = $ninja + ';' + $env:PATH
        $env:PATH
        'PATH=' + $env:PATH >> $env:GITHUB_ENV

    - name: Configure CMake
      run: cmake -A ${{ env.BUILD_PLATFORM }} -B ${{ env.BUILD_DIR }} -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.type }}

    - name: Build
      run: cmake --build ${{ env.BUILD_DIR }} --config ${{ matrix.type }}

    - name: Hash
      run: ('EXE_HASH=' + (Get-FileHash -Algorithm SHA256 ${{ env.RESULT }}.exe).Hash.ToLower()) >> $Env:GITHUB_ENV

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CryMP-Client${{ matrix.bits }}-${{ env.EXE_HASH }}
        path: |
          ${{ env.RESULT }}.exe
          ${{ env.RESULT }}.pdb

  notify_master:
    if: github.ref == 'refs/heads/master'
    runs-on: windows-latest

    needs: build_windows_msvc

    steps:
    - name: Notify CryMP master server
      env:
        SECRET: ${{ secrets.MASTER_NOTIFY_SECRET }}
      run: |
        $timestamp = [DateTimeOffset]::Now.ToUnixTimeSeconds().ToString()
        $hmac_sha256 = New-Object System.Security.Cryptography.HMACSHA256
        $hmac_sha256.key = [Text.Encoding]::ASCII.GetBytes($env:SECRET)
        $signature = $hmac_sha256.ComputeHash([Text.Encoding]::ASCII.GetBytes($timestamp))
        $signature = [BitConverter]::ToString($signature).Replace('-', '').ToLower()
        $params = @{
          Method = "POST"
          Uri = "https://crymp.nullptr.one/api/release?context=dev&time=$timestamp&signature=$signature"
        }
        Invoke-RestMethod @params
