################################################################################
# Reusable workflow for notifying the CryMP master server about new builds
################################################################################

name: Notify

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
    secrets:
      key:
        required: true

jobs:
  crymp:
    runs-on: ubuntu-latest
    steps:
      - name: Notify CryMP master server
        run: |
          context='${{ inputs.context }}'
          timestamp=$(date +%s)
          signature=$(printf %s "$timestamp" | openssl sha256 -hmac '${{ secrets.key }}' | sed 's/^.* //')
          curl --silent --show-error --fail-with-body --request POST \
            "https://crymp.nullptr.one/api/release?context=$context&time=$timestamp&signature=$signature"
