################################################################################
# Reusable workflow for dispatching the notify workflow
################################################################################

name: Notify dispatch

on:
  workflow_call:
    inputs:
      context:
        description: Build type
        required: true
        type: string
      artifact_32:
        description: Name of 32-bit build artifact
        required: true
        type: string
      artifact_64:
        description: Name of 64-bit build artifact
        required: true
        type: string

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch notify workflow
        run: |
          curl --silent --show-error --fail-with-body --request POST \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'Content-Type: application/json' \
            --data '{"ref":"master","inputs":{
              "context":"${{ inputs.context }}",
              "artifact_32":"${{ inputs.artifact_32 }}",
              "artifact_64":"${{ inputs.artifact_64 }}"
              }}' \
            'https://api.github.com/repos/crymp-net/client-server/actions/workflows/notify.yml/dispatches'
