################################################################################
# Push workflow running on a push to any branch
################################################################################

name: Push

on:
  push:
    branches:
      - '**'

jobs:
  build_32:
    uses: crymp-net/client-server/.github/workflows/build.yml@master
    with:
      bits: 32
      type: RelWithDebInfo

  build_64:
    uses: crymp-net/client-server/.github/workflows/build.yml@master
    with:
      bits: 64
      type: RelWithDebInfo

  notify:
    if: github.ref == 'refs/heads/master'
    needs:
      - build_32
      - build_64
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch notify workflow
        run: |
          curl --silent --show-error --fail-with-body --request POST \
            --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --url 'https://api.github.com/repos/crymp-net/client-server/actions/workflows/notify.yml/dispatches' \
            --data '{"ref":"master","inputs":{"context":"dev",
              "artifact_32":"${{ needs.build_32.outputs.artifact_name }}",
              "artifact_64":"${{ needs.build_64.outputs.artifact_name }}"}}'
