################################################################################
# Push workflow running on a push to any branch
################################################################################

name: Push

on:
  push:
    branches:
      - '**'

jobs:
  build_32:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      bits: 32
      type: RelWithDebInfo

  build_64:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      bits: 64
      type: RelWithDebInfo

  upload:
    if: github.ref == 'refs/heads/master'
    needs:
      - build_32
      - build_64
    uses: ./.github/workflows/upload.yml
    secrets: inherit
    with:
      context: dev
      artifact_32: ${{ needs.build_32.outputs.artifact_name }}
      artifact_64: ${{ needs.build_64.outputs.artifact_name }}
