################################################################################
# Push workflow running on a push to any branch
################################################################################

name: Push

on:
  push:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        bits: [ 32, 64 ]
        type: [ RelWithDebInfo ]
    uses: crymp-net/client-server/.github/workflows/build.yml@master
    with:
      bits: ${{ matrix.bits }}
      type: ${{ matrix.type }}

  notify:
    if: github.ref == 'refs/heads/master'
    needs: build
    uses: crymp-net/client-server/.github/workflows/notify.yml@master
    with:
      context: dev
    secrets:
      key: ${{ secrets.MASTER_NOTIFY_KEY }}
