name: Release

on:
  push:
    tags:
    - v*

jobs:
  build_32:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -A Win32 -B ${{ github.workspace }}/Build32 -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{ github.workspace }}/Build32 --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CryMP-Client32-Release
        path: ${{ github.workspace }}/Build32/Release/CryMP-Client32.exe

  build_64:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -A x64 -B ${{ github.workspace }}/Build64 -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{ github.workspace }}/Build64 --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: CryMP-Client64-Release
        path: ${{ github.workspace }}/Build64/Release/CryMP-Client64.exe

  do_release:
    runs-on: ubuntu-latest

    needs:
    - build_32
    - build_64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get changelog
      run: |
        echo "CHANGELOG<<EOF" >> $GITHUB_ENV
        sed -n "/^## \[${{ github.ref_name }}\] /,/^## /p" ${{ github.workspace }}/CHANGELOG.md | sed '1d;$d' >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Download 32-bit build artifacts
      uses: actions/download-artifact@v3
      with:
        name: CryMP-Client32-Release

    - name: Download 64-bit build artifacts
      uses: actions/download-artifact@v3
      with:
        name: CryMP-Client64-Release

    - name: Make it executable
      # make Linux users happy
      run: chmod 755 CryMP-Client32.exe CryMP-Client64.exe

    - name: Create ZIP file
      run: zip crymp-client-${{ github.ref_name }}-build.zip CryMP-Client32.exe CryMP-Client64.exe

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref_name }}
        body: ${{ env.CHANGELOG }}
        draft: false
        prerelease: false

    - name: Add the ZIP file to the release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: crymp-client-${{ github.ref_name }}-build.zip
        asset_name: crymp-client-${{ github.ref_name }}-build.zip
        asset_content_type: application/zip

    - name: Notify CryMP master server
      run: curl --silent --show-error -X POST "https://crymp.net/api/release"
